name: graduation
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
 

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
assets:
  - assets/
  - assets/images/
fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/InterMedium.ttf
        weight: 500
      - asset: assets/fonts/InterBold.ttf
        weight: 700
      - asset: assets/fonts/InterRegular.ttf
        weight: 400
      - asset: assets/fonts/InterSemiBold.ttf
        weight: 600
  - family: Work Sans
    fonts:
      - asset: assets/fonts/WorkSansRomanSemiBold.ttf
        weight: 600


